/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LogsHistoryIndexImport } from './routes/logs-history/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as BooksIndexImport } from './routes/books/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as UserWrapperImport } from './routes/user/_wrapper'
import { Route as BooksIdImport } from './routes/books/$id'
import { Route as UserWrapperIndexImport } from './routes/user/_wrapper/index'
import { Route as AdminRentalsIndexImport } from './routes/admin/rentals/index'
import { Route as AdminBooksIndexImport } from './routes/admin/books/index'
import { Route as AdminRentalsIdImport } from './routes/admin/rentals/$id'
import { Route as UserWrapperStatsIndexImport } from './routes/user/_wrapper/stats/index'
import { Route as UserWrapperRentalsIndexImport } from './routes/user/_wrapper/rentals/index'
import { Route as UserWrapperDetailsIndexImport } from './routes/user/_wrapper/details/index'
import { Route as UserWrapperDeleteAccountIndexImport } from './routes/user/_wrapper/delete-account/index'
import { Route as AdminBooksEditIdImport } from './routes/admin/books/edit/$id'

// Create Virtual Routes

const UserImport = createFileRoute('/user')()

// Create/Update Routes

const UserRoute = UserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LogsHistoryIndexRoute = LogsHistoryIndexImport.update({
  id: '/logs-history/',
  path: '/logs-history/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const BooksIndexRoute = BooksIndexImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const UserWrapperRoute = UserWrapperImport.update({
  id: '/_wrapper',
  getParentRoute: () => UserRoute,
} as any)

const BooksIdRoute = BooksIdImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRoute,
} as any)

const UserWrapperIndexRoute = UserWrapperIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserWrapperRoute,
} as any)

const AdminRentalsIndexRoute = AdminRentalsIndexImport.update({
  id: '/admin/rentals/',
  path: '/admin/rentals/',
  getParentRoute: () => rootRoute,
} as any)

const AdminBooksIndexRoute = AdminBooksIndexImport.update({
  id: '/admin/books/',
  path: '/admin/books/',
  getParentRoute: () => rootRoute,
} as any)

const AdminRentalsIdRoute = AdminRentalsIdImport.update({
  id: '/admin/rentals/$id',
  path: '/admin/rentals/$id',
  getParentRoute: () => rootRoute,
} as any)

const UserWrapperStatsIndexRoute = UserWrapperStatsIndexImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => UserWrapperRoute,
} as any)

const UserWrapperRentalsIndexRoute = UserWrapperRentalsIndexImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => UserWrapperRoute,
} as any)

const UserWrapperDetailsIndexRoute = UserWrapperDetailsIndexImport.update({
  id: '/details/',
  path: '/details/',
  getParentRoute: () => UserWrapperRoute,
} as any)

const UserWrapperDeleteAccountIndexRoute =
  UserWrapperDeleteAccountIndexImport.update({
    id: '/delete-account/',
    path: '/delete-account/',
    getParentRoute: () => UserWrapperRoute,
  } as any)

const AdminBooksEditIdRoute = AdminBooksEditIdImport.update({
  id: '/admin/books/edit/$id',
  path: '/admin/books/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/user/_wrapper': {
      id: '/user/_wrapper'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserWrapperImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/logs-history/': {
      id: '/logs-history/'
      path: '/logs-history'
      fullPath: '/logs-history'
      preLoaderRoute: typeof LogsHistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/rentals/$id': {
      id: '/admin/rentals/$id'
      path: '/admin/rentals/$id'
      fullPath: '/admin/rentals/$id'
      preLoaderRoute: typeof AdminRentalsIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/rentals/': {
      id: '/admin/rentals/'
      path: '/admin/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/_wrapper/': {
      id: '/user/_wrapper/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserWrapperIndexImport
      parentRoute: typeof UserWrapperImport
    }
    '/admin/books/edit/$id': {
      id: '/admin/books/edit/$id'
      path: '/admin/books/edit/$id'
      fullPath: '/admin/books/edit/$id'
      preLoaderRoute: typeof AdminBooksEditIdImport
      parentRoute: typeof rootRoute
    }
    '/user/_wrapper/delete-account/': {
      id: '/user/_wrapper/delete-account/'
      path: '/delete-account'
      fullPath: '/user/delete-account'
      preLoaderRoute: typeof UserWrapperDeleteAccountIndexImport
      parentRoute: typeof UserWrapperImport
    }
    '/user/_wrapper/details/': {
      id: '/user/_wrapper/details/'
      path: '/details'
      fullPath: '/user/details'
      preLoaderRoute: typeof UserWrapperDetailsIndexImport
      parentRoute: typeof UserWrapperImport
    }
    '/user/_wrapper/rentals/': {
      id: '/user/_wrapper/rentals/'
      path: '/rentals'
      fullPath: '/user/rentals'
      preLoaderRoute: typeof UserWrapperRentalsIndexImport
      parentRoute: typeof UserWrapperImport
    }
    '/user/_wrapper/stats/': {
      id: '/user/_wrapper/stats/'
      path: '/stats'
      fullPath: '/user/stats'
      preLoaderRoute: typeof UserWrapperStatsIndexImport
      parentRoute: typeof UserWrapperImport
    }
  }
}

// Create and export the route tree

interface UserWrapperRouteChildren {
  UserWrapperIndexRoute: typeof UserWrapperIndexRoute
  UserWrapperDeleteAccountIndexRoute: typeof UserWrapperDeleteAccountIndexRoute
  UserWrapperDetailsIndexRoute: typeof UserWrapperDetailsIndexRoute
  UserWrapperRentalsIndexRoute: typeof UserWrapperRentalsIndexRoute
  UserWrapperStatsIndexRoute: typeof UserWrapperStatsIndexRoute
}

const UserWrapperRouteChildren: UserWrapperRouteChildren = {
  UserWrapperIndexRoute: UserWrapperIndexRoute,
  UserWrapperDeleteAccountIndexRoute: UserWrapperDeleteAccountIndexRoute,
  UserWrapperDetailsIndexRoute: UserWrapperDetailsIndexRoute,
  UserWrapperRentalsIndexRoute: UserWrapperRentalsIndexRoute,
  UserWrapperStatsIndexRoute: UserWrapperStatsIndexRoute,
}

const UserWrapperRouteWithChildren = UserWrapperRoute._addFileChildren(
  UserWrapperRouteChildren,
)

interface UserRouteChildren {
  UserWrapperRoute: typeof UserWrapperRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserWrapperRoute: UserWrapperRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$id': typeof BooksIdRoute
  '/user': typeof UserWrapperRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/login': typeof LoginIndexRoute
  '/logs-history': typeof LogsHistoryIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/rentals/$id': typeof AdminRentalsIdRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/rentals': typeof AdminRentalsIndexRoute
  '/user/': typeof UserWrapperIndexRoute
  '/admin/books/edit/$id': typeof AdminBooksEditIdRoute
  '/user/delete-account': typeof UserWrapperDeleteAccountIndexRoute
  '/user/details': typeof UserWrapperDetailsIndexRoute
  '/user/rentals': typeof UserWrapperRentalsIndexRoute
  '/user/stats': typeof UserWrapperStatsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$id': typeof BooksIdRoute
  '/user': typeof UserWrapperIndexRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/login': typeof LoginIndexRoute
  '/logs-history': typeof LogsHistoryIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/rentals/$id': typeof AdminRentalsIdRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/rentals': typeof AdminRentalsIndexRoute
  '/admin/books/edit/$id': typeof AdminBooksEditIdRoute
  '/user/delete-account': typeof UserWrapperDeleteAccountIndexRoute
  '/user/details': typeof UserWrapperDetailsIndexRoute
  '/user/rentals': typeof UserWrapperRentalsIndexRoute
  '/user/stats': typeof UserWrapperStatsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/books/$id': typeof BooksIdRoute
  '/user': typeof UserRouteWithChildren
  '/user/_wrapper': typeof UserWrapperRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logs-history/': typeof LogsHistoryIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/rentals/$id': typeof AdminRentalsIdRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
  '/user/_wrapper/': typeof UserWrapperIndexRoute
  '/admin/books/edit/$id': typeof AdminBooksEditIdRoute
  '/user/_wrapper/delete-account/': typeof UserWrapperDeleteAccountIndexRoute
  '/user/_wrapper/details/': typeof UserWrapperDetailsIndexRoute
  '/user/_wrapper/rentals/': typeof UserWrapperRentalsIndexRoute
  '/user/_wrapper/stats/': typeof UserWrapperStatsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books/$id'
    | '/user'
    | '/admin'
    | '/books'
    | '/login'
    | '/logs-history'
    | '/register'
    | '/admin/rentals/$id'
    | '/admin/books'
    | '/admin/rentals'
    | '/user/'
    | '/admin/books/edit/$id'
    | '/user/delete-account'
    | '/user/details'
    | '/user/rentals'
    | '/user/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books/$id'
    | '/user'
    | '/admin'
    | '/books'
    | '/login'
    | '/logs-history'
    | '/register'
    | '/admin/rentals/$id'
    | '/admin/books'
    | '/admin/rentals'
    | '/admin/books/edit/$id'
    | '/user/delete-account'
    | '/user/details'
    | '/user/rentals'
    | '/user/stats'
  id:
    | '__root__'
    | '/'
    | '/books/$id'
    | '/user'
    | '/user/_wrapper'
    | '/admin/'
    | '/books/'
    | '/login/'
    | '/logs-history/'
    | '/register/'
    | '/admin/rentals/$id'
    | '/admin/books/'
    | '/admin/rentals/'
    | '/user/_wrapper/'
    | '/admin/books/edit/$id'
    | '/user/_wrapper/delete-account/'
    | '/user/_wrapper/details/'
    | '/user/_wrapper/rentals/'
    | '/user/_wrapper/stats/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksIdRoute: typeof BooksIdRoute
  UserRoute: typeof UserRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LogsHistoryIndexRoute: typeof LogsHistoryIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  AdminRentalsIdRoute: typeof AdminRentalsIdRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminRentalsIndexRoute: typeof AdminRentalsIndexRoute
  AdminBooksEditIdRoute: typeof AdminBooksEditIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksIdRoute: BooksIdRoute,
  UserRoute: UserRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LogsHistoryIndexRoute: LogsHistoryIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AdminRentalsIdRoute: AdminRentalsIdRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminRentalsIndexRoute: AdminRentalsIndexRoute,
  AdminBooksEditIdRoute: AdminBooksEditIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books/$id",
        "/user",
        "/admin/",
        "/books/",
        "/login/",
        "/logs-history/",
        "/register/",
        "/admin/rentals/$id",
        "/admin/books/",
        "/admin/rentals/",
        "/admin/books/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books/$id": {
      "filePath": "books/$id.tsx"
    },
    "/user": {
      "filePath": "user",
      "children": [
        "/user/_wrapper"
      ]
    },
    "/user/_wrapper": {
      "filePath": "user/_wrapper.tsx",
      "parent": "/user",
      "children": [
        "/user/_wrapper/",
        "/user/_wrapper/delete-account/",
        "/user/_wrapper/details/",
        "/user/_wrapper/rentals/",
        "/user/_wrapper/stats/"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/books/": {
      "filePath": "books/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/logs-history/": {
      "filePath": "logs-history/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/admin/rentals/$id": {
      "filePath": "admin/rentals/$id.tsx"
    },
    "/admin/books/": {
      "filePath": "admin/books/index.tsx"
    },
    "/admin/rentals/": {
      "filePath": "admin/rentals/index.tsx"
    },
    "/user/_wrapper/": {
      "filePath": "user/_wrapper/index.tsx",
      "parent": "/user/_wrapper"
    },
    "/admin/books/edit/$id": {
      "filePath": "admin/books/edit/$id.tsx"
    },
    "/user/_wrapper/delete-account/": {
      "filePath": "user/_wrapper/delete-account/index.tsx",
      "parent": "/user/_wrapper"
    },
    "/user/_wrapper/details/": {
      "filePath": "user/_wrapper/details/index.tsx",
      "parent": "/user/_wrapper"
    },
    "/user/_wrapper/rentals/": {
      "filePath": "user/_wrapper/rentals/index.tsx",
      "parent": "/user/_wrapper"
    },
    "/user/_wrapper/stats/": {
      "filePath": "user/_wrapper/stats/index.tsx",
      "parent": "/user/_wrapper"
    }
  }
}
ROUTE_MANIFEST_END */
